use_frameworks!

platform :ios, '10.0'

target 'lsj-FileManager_Example' do
  pod 'lsj-FileManager', :path => '../'

  target 'lsj-FileManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
